### ISSUE TITLE
Sky Factory 2.5/Botania garden of glass/multiplayer island

### ISSUE THREAD

**Issue by Atomics1911** [TheCricket/FTB-Islands#25]
Having issues trying to configure the multiplayer island so they either start as garden of glass islands or can be transformed into one. After I try and transform one into a GoG island, it will revert to a 1 block 1 tree leaving it or resetting server.

**Comment by LezChap** [comment]
> After I try and transform one into a GoG island, it will revert to a 1 block 1 tree leaving it or resetting server.

Can you explain what you're trying to do with commands, configs, and actions in game/console?

If you want the 3x4x3 GoG island with the Living Root and water source, you have to use the "/botania-skyblock-spread -playername-" command right now.  If you want players to be able to use the "island_join" command after that, you need to manually add the coordinates/island name to the "local\islands.json" file (I don't believe there's a command to reload the islands from file at this time, so you'll have to restart the server).

**Comment by Atomics1911** [comment]
Well only setting I changed in ftb_island.cfg is the Sky Factory to true. Yes I use the /botania-skyblock-spread @p[r=3] to transform the island once I create it.

Don't really know much about .json file, pretty new to the server side of MC.

**Comment by LezChap** [comment]
I think the problem is you are misunderstanding how the commands in the multiple mods function and interact.  /botania-skyblock-spread creates a platform at random coordinates within 100k (I think, the number doesn't matter) of origin and teleports the player there.  The FTB Islands /island_create will create an island at every 1000-block intersection (by default), so there'll be one at 1000, 1000, the next is at 1000, 0, the next at 1000, -1000, etc.  This island is a tree with a single block of dirt (when Sky Factory is set to true).  

Check your coordinates when you use the botania-skyblock-spread (you can use the playername, not just @p[r=3]), and the island_join commands, and you'll see that they aren't linking to the same location in the world.  In order to get the island created by botania-skyblock-spread to work with island_join, don't even bother with /island_create...edit your islands.json file like I said in my previous comment.

For example, if botania-skyblock-spread created and island at 83750, 86, 56519, you'd make the islands.json look like this to give me an island:
`{"default":{"x":0,"y":60,"z":0},"LezChap":{"x":83750,"y":86,"z":56519}}`

**Comment by Atomics1911** [comment]
Ok don't know much about scripting...this good for my island.json or missing something?

{"default":{"x":0,"y":60,"z":0},"aegontv":{"x":35840,"y":86,"z":-99436}}
{"default":{"x":0,"y":60,"z":0},"theundeadlords":{"x":-19602,"y":86,"z":88376}}
{"default":{"x":0,"y":60,"z":0},"renaris":{"x":47655,"y":86,"z":-96278}}

**Comment by kolatra** [comment]
You don't need to add the default before each one, the default is in place to prevent some loading issues.

**Comment by kolatra** [comment]
Try putting this in your islands file.

{"aegontv":{"x":35840,"y":86,"z":-99436},"theundeadlords":{"x":-19602,"y":86,"z":88376},"renaris":{"x":47655,"y":86,"z":-96278}}

**Comment by Atomics1911** [comment]
Thanks, everything seems to be working now. Is there a way to automate it for new players joining?

**Comment by LezChap** [comment]
I can't think of a good way to automate new players joining, and giving them GoG Islands as of the latest release.
